#!/usr/bin/python

import numpy as np
import itertools as it

import group

def main():
    prefs = [[0.,0.,0.], [0.,0.,1.], [1.,1.,0.], [1.,1.,1.]]
    #prefs = np.asarray(prefs)
    p2max = 4
    groups = []

    # initialize groups
    U3 = np.asarray([[0,0,-1.],[1.j,0,0],[0,1,0]])
    for p2 in range(p2max):
        try:
            _g = group.TOh.read(p2=p2)
        except IOError:
            _g = group.TOh(pref=prefs[p2], irreps=True, U3=U3)
            _g.save()
        groups.append(_g)
        print("p^2 = %d" % p2)
        print(_g.irrepsname)

    for g in groups:
        print(g.name)
        print(g.p2)
        # spinor darstellungen:
        # E1g, E1u
        # E2g, E2u
        # F1g, F1u
        m = g.irreps[g.irrepsname.index("E1g")].mx
        e = g.elements
        for _m, _e in zip(m, e):
            print(_e)
            print(_m)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
