#!/usr/bin/python

import numpy as np
import itertools as it

import group

def main():
    p2max = 4
    jmax = 3
    groups = []

    # initialize groups
    for p2 in range(p2max):
        g = group.OhGroup(p2=p2, instances=True)
        groups.append(g)

    # calc coefficients
    print(" CMF ".center(40, "*"))
    irnames = groups[0].lirreps
    for p in range(p2max):
        cgs = group.OhCG(0, p, p, groups)
        for ir in irnames:
            a, b, c = cgs.get_pion_cg(ir)
            if b is not None:
                print(ir)
                group.cg_to_pandas(b,c)
                print ' '

    print(" MF1 ".center(40, "*"))
    irnames = groups[1].lirreps
    for i, j in it.product(range(p2max), repeat=2):
        if j-i != 1:
            continue
        cgs = group.OhCG(1, i, j, groups)
        print("%d x %d -> 1" % (i, j))
        for ir in irnames:
            a, b, c = cgs.get_pion_cg(ir)
            if b is not None:
                print(ir)
                group.cg_to_pandas(b,c)
                print ' '

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
