#!/usr/bin/python

import numpy as np

import group

def main():
    np.set_printoptions(suppress=True)

    print(" CMF ".center(50, "*"))
    g = OhGroup(instances=False)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
